### ISSUE TITLE
debug blocks?

### ISSUE THREAD

**Issue by xloem** [pothosware/pothos-blocks#34]
It would be nice to have debug blocks which log labels and messages as in gnuradio

**Comment by guruofquality** [comment]
* Are you thinking of a sink block that logs the incoming buffer + size, associated labels, or message?
* Any configurabilty other than blind logging? Like specific filters for labels?
* Related issue: https://github.com/pothosware/pothos-widgets/issues/13

**Comment by xloem** [comment]
This should probably be met by pothosware/pothos-widgets#13 .  It would just be expanded to allow the stream to continually run, and keep generating log entries when a matching tag or message is found.

My personal attempt to understand the label stream has been met for now by the Label to Message block, which I can plug into a textbox via Message to Signal.
