### ISSUE TITLE
blocks to convert between labels, signals, messages

### ISSUE THREAD

**Issue by xloem** [pothosware/pothos-blocks#35]

**Comment by guruofquality** [comment]
I guess you found the event blocks here: https://github.com/pothosware/pothos-blocks/tree/master/event

Is the label to message what you were missing? Anything else in this realm worthwhile?

**Comment by xloem** [comment]
This is what I was missing, although I suppose a Label to Signal block would complete things.

The behavior of Label to Message sends out a message for every single matching label.  I didn't know the behavior of the system well enough to know if that was a wise idea, or if perhaps you'd want to limit the rate to some frequency, or respond to a signal the way Signal Probe does.

**Comment by guruofquality** [comment]
The message/event system is the same in the scheduler. The only distinction is how the API exposes it to the user. So the label to message block can just as easily be plugged into a block with a slot.
