### ISSUE TITLE
Waveform Source outputs a constant function if frequency is too low

### ISSUE THREAD

**Issue by xloem** [pothosware/pothos-blocks#36]
A quick debug shows that `_step` becomes zero, so `_index` is never increased in the work function.

**Comment by guruofquality** [comment]
Can you share the sample rate and waveform rate that caused this. There is a little note about the resolution parameter here. Was resolution on automatic or something else?

```
|param res[Resolution] The resolution of the internal wave table (0.0 for automatic).
 * When unspecified, the wave table size will be configured for the user's requested frequency.
 * Specify a minimum resolution in Hz to fix the size of the wave table.
```

**Comment by xloem** [comment]
Resolution was automatic; sample rate 1e6; frequency < 0.5 causes constant output.  In the debug the resolution was 4096 I believe.

**Comment by xloem** [comment]
This is coded for; the stepUpdate function aborts and allows the step size to be 0 if the table size would exceed a million: https://github.com/pothosware/pothos-comms/blob/master/waveform/WaveformSource.cpp#L191

Is there a proper way to display to the user that this is an invalid frequency?

**Comment by guruofquality** [comment]
The table lookup has a limited resolution. Small enough and eventually you cant allocate enough space for the table. std::sin and cos can be expensive, so the table is a nice optimization, but I can see where it breaks down. We might need a block that doesn't use a table, but performs the live calculation. Or make that a configurable option at least in the waveform source.

Anyway, for this its probably best to log a warning when the calculated _step is significantly different than the (_freq/_rate). I want to throw a range error, but theres some need here to be careful that the error is only thrown after the freq, rate, and resolution are applied. We could accidentalaly cause the error while still applying settings. The FIR designer actually has a similar design, and it uses ``` if (not this->isActive())``` to avoid doing calculations until the block is activated.

**Comment by xloem** [comment]
Note: could also use a sin/cos table rather than a waveform table.

**Comment by guruofquality** [comment]
* Update, this condition is checked now: https://github.com/pothosware/pothos/commit/d80a9efbfa19c572a8d883849d6fc1f6cd788850
* New issue for improving this further: https://github.com/pothosware/pothos-comms/issues/11
