### ISSUE TITLE
Converter block loses samples

### ISSUE THREAD

**Issue by kevinmehall** [pothosware/pothos-blocks#43]
When there is backpressure, the converter block seems to lose samples:

Graph: https://kevinmehall.net/tmp/convert.pothos
![screenshot from 2017-03-26 18-13-55](https://cloud.githubusercontent.com/assets/119951/24337314/795c831a-1250-11e7-80f3-1ee27ef9517c.png)

[This line](https://github.com/pothosware/pothos-blocks/blob/979790a9a805081d04ecafe61a10d1e5353daef4/stream/Converter.cpp#L46) looks suspicious. I tried replacing it with `inputPort->consume(numElems);` just above `outputPort->produce(numElems);`, but that made it stop after the first buffer.

**Comment by kevinmehall** [comment]
Yes:
```diff
diff --git a/stream/Converter.cpp b/stream/Converter.cpp
index e0f8cd2..7ed1e53 100644
--- a/stream/Converter.cpp
+++ b/stream/Converter.cpp
@@ -43,7 +43,6 @@ public:
     {
         auto inputPort = this->input(0);
         auto outputPort = this->output(0);
-        inputPort->consume(inputPort->elements());
 
         //got a packet message
         if (inputPort->hasMessage())
@@ -61,6 +60,7 @@ public:
             const auto &outBuff = outputPort->buffer();
             size_t numElems = std::min(outBuff.elements(), buff.elements());
             buff.convert(outBuff, numElems);
+            inputPort->consume(numElems);
             outputPort->produce(numElems);
         }
     }
```

**Comment by guruofquality** [comment]
Thanks for pointing that out. Should be fixed now. Once I get the number of elements, I had to convert it back to bytes, the consume call takes bytes because its type was not specified by the setupInput()
